
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VPaned vpaned1;
	private global::Gtk.VBox vbox1;
	private global::Gtk.Notebook notebook1;
	private global::Gtk.VBox vbox2;
	private global::Gtk.HBox hbox3;
	private global::Gtk.RadioButton ManualPort;
	private global::Gtk.Label label3;
	private global::Gtk.SpinButton HostPortNum;
	private global::Gtk.Label label7;
	private global::Gtk.Fixed fixed2;
	private global::Gtk.HBox hbox1;
	private global::Gtk.RadioButton PortFromList;
	private global::Gtk.ComboBox HostList;
	private global::Gtk.Fixed fixed3;
	private global::Gtk.Button RefreshHostList;
	private global::Gtk.Button StartScan;
	private global::Gtk.Label label1;
	private global::Gtk.VBox vbox4;
	private global::Gtk.HBox hbox7;
	private global::Gtk.Label label10;
	private global::Gtk.Entry ImageFilePath;
	private global::Gtk.FileChooserButton ImageFileOpenButton;
	private global::Gtk.HBox hbox8;
	private global::Gtk.RadioButton ManualDevName;
	private global::Gtk.Label label11;
	private global::Gtk.Entry DevWord;
	private global::Gtk.Label label12;
	private global::Gtk.Fixed fixed6;
	private global::Gtk.HBox hbox9;
	private global::Gtk.RadioButton DevNameFromList;
	private global::Gtk.ComboBox DevList;
	private global::Gtk.Fixed fixed7;
	private global::Gtk.Button RefreshDevList;
	private global::Gtk.Button UpackImage;
	private global::Gtk.HBox hbox10;
	private global::Gtk.Label label13;
	private global::Gtk.ProgressBar UnpackImageProgress;
	private global::Gtk.Label label2;
	private global::Gtk.VBox vbox6;
	private global::Gtk.HBox hbox13;
	private global::Gtk.Label label15;
	private global::Gtk.Entry SaveImageFilePath;
	private global::Gtk.Button SaveImageButton;
	private global::Gtk.HBox hbox14;
	private global::Gtk.RadioButton ManualSaveDevName;
	private global::Gtk.Label label17;
	private global::Gtk.Entry SaveDevWord;
	private global::Gtk.Label label18;
	private global::Gtk.Fixed fixed10;
	private global::Gtk.HBox hbox15;
	private global::Gtk.RadioButton SaveDevNameFromList;
	private global::Gtk.ComboBox SaveDevList;
	private global::Gtk.Fixed fixed11;
	private global::Gtk.Button RefreshSaveDevList;
	private global::Gtk.Button SaveImageBtn;
	private global::Gtk.HBox hbox16;
	private global::Gtk.Label label19;
	private global::Gtk.ProgressBar CreateImageProgress;
	private global::Gtk.Label label6;
	private global::Gtk.VBox vbox5;
	private global::Gtk.HBox hbox11;
	private global::Gtk.RadioButton ManualDelDevName;
	private global::Gtk.Label label4;
	private global::Gtk.Entry DelDevWord;
	private global::Gtk.Label label14;
	private global::Gtk.Fixed fixed8;
	private global::Gtk.HBox hbox12;
	private global::Gtk.RadioButton DelDevNameFromList;
	private global::Gtk.ComboBox DelDevList;
	private global::Gtk.Fixed fixed9;
	private global::Gtk.Button RefreshDelDevWord;
	private global::Gtk.Button DisconnectDeviceBtn;
	private global::Gtk.Label label5;
	private global::Gtk.VBox vbox3;
	private global::Gtk.HBox hbox4;
	private global::Gtk.Label label8;
	private global::Gtk.Entry CfgCmdShell;
	private global::Gtk.HBox hbox5;
	private global::Gtk.Label label9;
	private global::Gtk.Entry CfgPartImage;
	private global::Gtk.VBox vbox7;
	private global::Gtk.Fixed fixed5;
	private global::Gtk.HBox hbox6;
	private global::Gtk.Fixed fixed4;
	private global::Gtk.Button ApplyConfig;
	private global::Gtk.Label label16;
	private global::Gtk.Frame frame1;
	private global::Gtk.Alignment GtkAlignment;
	private global::Gtk.VBox vbox8;
	private global::Gtk.HBox hbox17;
	private global::Gtk.Fixed fixed1;
	private global::Gtk.HBox hbox19;
	private global::Gtk.Fixed fixed13;
	private global::Gtk.Fixed fixed14;
	private global::Gtk.HBox hbox20;
	private global::Gtk.Button AutoSaveImage;
	private global::Gtk.Button AutoUnpackImage;
	private global::Gtk.Label GtkLabel24;
	private global::Gtk.VBox vbox9;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.NodeView LogView;
	private global::Gtk.HBox hbox21;
	private global::Gtk.Button ShowAbout;
	private global::Gtk.Fixed fixed15;
	private global::Gtk.Button ClearLog;
	private global::Gtk.Button SaveLog;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vpaned1 = new global::Gtk.VPaned ();
		this.vpaned1.CanFocus = true;
		this.vpaned1.Name = "vpaned1";
		this.vpaned1.Position = 292;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 0;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.ManualPort = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Указать вручную"));
		this.ManualPort.CanFocus = true;
		this.ManualPort.Name = "ManualPort";
		this.ManualPort.DrawIndicator = true;
		this.ManualPort.UseUnderline = true;
		this.ManualPort.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.hbox3.Add (this.ManualPort);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.ManualPort]));
		w1.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("host(");
		this.hbox3.Add (this.label3);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label3]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.HostPortNum = new global::Gtk.SpinButton (0, 100, 1);
		this.HostPortNum.WidthRequest = 50;
		this.HostPortNum.CanFocus = true;
		this.HostPortNum.Name = "HostPortNum";
		this.HostPortNum.Adjustment.PageIncrement = 10;
		this.HostPortNum.ClimbRate = 1;
		this.HostPortNum.Numeric = true;
		this.hbox3.Add (this.HostPortNum);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.HostPortNum]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString (")");
		this.hbox3.Add (this.label7);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label7]));
		w4.Position = 3;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		this.hbox3.Add (this.fixed2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.fixed2]));
		w5.PackType = ((global::Gtk.PackType)(1));
		w5.Position = 4;
		this.vbox2.Add (this.hbox3);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.PortFromList = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Выбрать из списка"));
		this.PortFromList.CanFocus = true;
		this.PortFromList.Name = "PortFromList";
		this.PortFromList.DrawIndicator = true;
		this.PortFromList.UseUnderline = true;
		this.PortFromList.Group = this.ManualPort.Group;
		this.hbox1.Add (this.PortFromList);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.PortFromList]));
		w7.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.HostList = global::Gtk.ComboBox.NewText ();
		this.HostList.WidthRequest = 100;
		this.HostList.Name = "HostList";
		this.hbox1.Add (this.HostList);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.HostList]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.fixed3 = new global::Gtk.Fixed ();
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		this.hbox1.Add (this.fixed3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.fixed3]));
		w9.PackType = ((global::Gtk.PackType)(1));
		w9.Position = 2;
		// Container child hbox1.Gtk.Box+BoxChild
		this.RefreshHostList = new global::Gtk.Button ();
		this.RefreshHostList.CanFocus = true;
		this.RefreshHostList.Name = "RefreshHostList";
		this.RefreshHostList.UseUnderline = true;
		this.RefreshHostList.Label = global::Mono.Unix.Catalog.GetString ("Обновить");
		this.hbox1.Add (this.RefreshHostList);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.RefreshHostList]));
		w10.PackType = ((global::Gtk.PackType)(1));
		w10.Position = 3;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox2.Add (this.hbox1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.StartScan = new global::Gtk.Button ();
		this.StartScan.CanFocus = true;
		this.StartScan.Name = "StartScan";
		this.StartScan.UseUnderline = true;
		this.StartScan.Label = global::Mono.Unix.Catalog.GetString ("Подключить");
		this.vbox2.Add (this.StartScan);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.StartScan]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		this.notebook1.Add (this.vbox2);
		// Notebook tab
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Обнаружение НЖМД");
		this.notebook1.SetTabLabel (this.vbox2, this.label1);
		this.label1.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Файл образа:");
		this.hbox7.Add (this.label10);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label10]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.ImageFilePath = new global::Gtk.Entry ();
		this.ImageFilePath.CanFocus = true;
		this.ImageFilePath.Name = "ImageFilePath";
		this.ImageFilePath.IsEditable = true;
		this.ImageFilePath.InvisibleChar = '•';
		this.hbox7.Add (this.ImageFilePath);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.ImageFilePath]));
		w15.Position = 1;
		// Container child hbox7.Gtk.Box+BoxChild
		this.ImageFileOpenButton = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Выберите файл"), ((global::Gtk.FileChooserAction)(0)));
		this.ImageFileOpenButton.Name = "ImageFileOpenButton";
		this.hbox7.Add (this.ImageFileOpenButton);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.ImageFileOpenButton]));
		w16.Position = 2;
		this.vbox4.Add (this.hbox7);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox7]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.ManualDevName = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Указать вручную"));
		this.ManualDevName.CanFocus = true;
		this.ManualDevName.Name = "ManualDevName";
		this.ManualDevName.DrawIndicator = true;
		this.ManualDevName.UseUnderline = true;
		this.ManualDevName.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.hbox8.Add (this.ManualDevName);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.ManualDevName]));
		w18.Position = 0;
		// Container child hbox8.Gtk.Box+BoxChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("sd(");
		this.hbox8.Add (this.label11);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label11]));
		w19.Position = 1;
		w19.Expand = false;
		w19.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.DevWord = new global::Gtk.Entry ();
		this.DevWord.WidthRequest = 30;
		this.DevWord.CanFocus = true;
		this.DevWord.Name = "DevWord";
		this.DevWord.IsEditable = true;
		this.DevWord.WidthChars = 0;
		this.DevWord.MaxLength = 2;
		this.DevWord.InvisibleChar = '•';
		this.hbox8.Add (this.DevWord);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.DevWord]));
		w20.Position = 2;
		w20.Expand = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.label12 = new global::Gtk.Label ();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString (")");
		this.hbox8.Add (this.label12);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label12]));
		w21.Position = 3;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.fixed6 = new global::Gtk.Fixed ();
		this.fixed6.Name = "fixed6";
		this.fixed6.HasWindow = false;
		this.hbox8.Add (this.fixed6);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.fixed6]));
		w22.PackType = ((global::Gtk.PackType)(1));
		w22.Position = 4;
		this.vbox4.Add (this.hbox8);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox8]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.DevNameFromList = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Выбрать из списка"));
		this.DevNameFromList.CanFocus = true;
		this.DevNameFromList.Name = "DevNameFromList";
		this.DevNameFromList.DrawIndicator = true;
		this.DevNameFromList.UseUnderline = true;
		this.DevNameFromList.Group = this.ManualDevName.Group;
		this.hbox9.Add (this.DevNameFromList);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.DevNameFromList]));
		w24.Position = 0;
		// Container child hbox9.Gtk.Box+BoxChild
		this.DevList = global::Gtk.ComboBox.NewText ();
		this.DevList.WidthRequest = 100;
		this.DevList.Name = "DevList";
		this.hbox9.Add (this.DevList);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.DevList]));
		w25.Position = 1;
		w25.Expand = false;
		w25.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.fixed7 = new global::Gtk.Fixed ();
		this.fixed7.Name = "fixed7";
		this.fixed7.HasWindow = false;
		this.hbox9.Add (this.fixed7);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.fixed7]));
		w26.PackType = ((global::Gtk.PackType)(1));
		w26.Position = 2;
		// Container child hbox9.Gtk.Box+BoxChild
		this.RefreshDevList = new global::Gtk.Button ();
		this.RefreshDevList.CanFocus = true;
		this.RefreshDevList.Name = "RefreshDevList";
		this.RefreshDevList.UseUnderline = true;
		this.RefreshDevList.Label = global::Mono.Unix.Catalog.GetString ("Обновить");
		this.hbox9.Add (this.RefreshDevList);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.RefreshDevList]));
		w27.PackType = ((global::Gtk.PackType)(1));
		w27.Position = 3;
		w27.Expand = false;
		w27.Fill = false;
		this.vbox4.Add (this.hbox9);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox9]));
		w28.Position = 2;
		w28.Expand = false;
		w28.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.UpackImage = new global::Gtk.Button ();
		this.UpackImage.CanFocus = true;
		this.UpackImage.Name = "UpackImage";
		this.UpackImage.UseUnderline = true;
		this.UpackImage.Label = global::Mono.Unix.Catalog.GetString ("Распаковать образ");
		this.vbox4.Add (this.UpackImage);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.UpackImage]));
		w29.Position = 3;
		w29.Expand = false;
		w29.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox ();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.label13 = new global::Gtk.Label ();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Прогресс выполнения:");
		this.hbox10.Add (this.label13);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.label13]));
		w30.Position = 0;
		w30.Expand = false;
		w30.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.UnpackImageProgress = new global::Gtk.ProgressBar ();
		this.UnpackImageProgress.HeightRequest = 30;
		this.UnpackImageProgress.Name = "UnpackImageProgress";
		this.hbox10.Add (this.UnpackImageProgress);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.UnpackImageProgress]));
		w31.Position = 1;
		this.vbox4.Add (this.hbox10);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox10]));
		w32.Position = 4;
		w32.Expand = false;
		w32.Fill = false;
		this.notebook1.Add (this.vbox4);
		global::Gtk.Notebook.NotebookChild w33 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox4]));
		w33.Position = 1;
		// Notebook tab
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Распаковка образа");
		this.notebook1.SetTabLabel (this.vbox4, this.label2);
		this.label2.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox13 = new global::Gtk.HBox ();
		this.hbox13.Name = "hbox13";
		this.hbox13.Spacing = 6;
		// Container child hbox13.Gtk.Box+BoxChild
		this.label15 = new global::Gtk.Label ();
		this.label15.Name = "label15";
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Файл образа:");
		this.hbox13.Add (this.label15);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.label15]));
		w34.Position = 0;
		w34.Expand = false;
		w34.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.SaveImageFilePath = new global::Gtk.Entry ();
		this.SaveImageFilePath.CanFocus = true;
		this.SaveImageFilePath.Name = "SaveImageFilePath";
		this.SaveImageFilePath.IsEditable = true;
		this.SaveImageFilePath.InvisibleChar = '•';
		this.hbox13.Add (this.SaveImageFilePath);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.SaveImageFilePath]));
		w35.Position = 1;
		// Container child hbox13.Gtk.Box+BoxChild
		this.SaveImageButton = new global::Gtk.Button ();
		this.SaveImageButton.CanFocus = true;
		this.SaveImageButton.Name = "SaveImageButton";
		this.SaveImageButton.UseUnderline = true;
		this.SaveImageButton.Label = global::Mono.Unix.Catalog.GetString ("Выбрать файл образа");
		this.hbox13.Add (this.SaveImageButton);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.SaveImageButton]));
		w36.Position = 2;
		w36.Expand = false;
		w36.Fill = false;
		this.vbox6.Add (this.hbox13);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox13]));
		w37.Position = 0;
		w37.Expand = false;
		w37.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox14 = new global::Gtk.HBox ();
		this.hbox14.Name = "hbox14";
		this.hbox14.Spacing = 6;
		// Container child hbox14.Gtk.Box+BoxChild
		this.ManualSaveDevName = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Указать вручную"));
		this.ManualSaveDevName.CanFocus = true;
		this.ManualSaveDevName.Name = "ManualSaveDevName";
		this.ManualSaveDevName.DrawIndicator = true;
		this.ManualSaveDevName.UseUnderline = true;
		this.ManualSaveDevName.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.hbox14.Add (this.ManualSaveDevName);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.ManualSaveDevName]));
		w38.Position = 0;
		// Container child hbox14.Gtk.Box+BoxChild
		this.label17 = new global::Gtk.Label ();
		this.label17.Name = "label17";
		this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("sd(");
		this.hbox14.Add (this.label17);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.label17]));
		w39.Position = 1;
		w39.Expand = false;
		w39.Fill = false;
		// Container child hbox14.Gtk.Box+BoxChild
		this.SaveDevWord = new global::Gtk.Entry ();
		this.SaveDevWord.WidthRequest = 30;
		this.SaveDevWord.CanFocus = true;
		this.SaveDevWord.Name = "SaveDevWord";
		this.SaveDevWord.IsEditable = true;
		this.SaveDevWord.WidthChars = 0;
		this.SaveDevWord.MaxLength = 2;
		this.SaveDevWord.InvisibleChar = '•';
		this.hbox14.Add (this.SaveDevWord);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.SaveDevWord]));
		w40.Position = 2;
		w40.Expand = false;
		// Container child hbox14.Gtk.Box+BoxChild
		this.label18 = new global::Gtk.Label ();
		this.label18.Name = "label18";
		this.label18.LabelProp = global::Mono.Unix.Catalog.GetString (")");
		this.hbox14.Add (this.label18);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.label18]));
		w41.Position = 3;
		w41.Expand = false;
		w41.Fill = false;
		// Container child hbox14.Gtk.Box+BoxChild
		this.fixed10 = new global::Gtk.Fixed ();
		this.fixed10.Name = "fixed10";
		this.fixed10.HasWindow = false;
		this.hbox14.Add (this.fixed10);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.fixed10]));
		w42.PackType = ((global::Gtk.PackType)(1));
		w42.Position = 4;
		this.vbox6.Add (this.hbox14);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox14]));
		w43.Position = 1;
		w43.Expand = false;
		w43.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox15 = new global::Gtk.HBox ();
		this.hbox15.Name = "hbox15";
		this.hbox15.Spacing = 6;
		// Container child hbox15.Gtk.Box+BoxChild
		this.SaveDevNameFromList = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Выбрать из списка"));
		this.SaveDevNameFromList.CanFocus = true;
		this.SaveDevNameFromList.Name = "SaveDevNameFromList";
		this.SaveDevNameFromList.DrawIndicator = true;
		this.SaveDevNameFromList.UseUnderline = true;
		this.SaveDevNameFromList.Group = this.ManualSaveDevName.Group;
		this.hbox15.Add (this.SaveDevNameFromList);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.SaveDevNameFromList]));
		w44.Position = 0;
		// Container child hbox15.Gtk.Box+BoxChild
		this.SaveDevList = global::Gtk.ComboBox.NewText ();
		this.SaveDevList.WidthRequest = 100;
		this.SaveDevList.Name = "SaveDevList";
		this.hbox15.Add (this.SaveDevList);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.SaveDevList]));
		w45.Position = 1;
		w45.Expand = false;
		w45.Fill = false;
		// Container child hbox15.Gtk.Box+BoxChild
		this.fixed11 = new global::Gtk.Fixed ();
		this.fixed11.Name = "fixed11";
		this.fixed11.HasWindow = false;
		this.hbox15.Add (this.fixed11);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.fixed11]));
		w46.PackType = ((global::Gtk.PackType)(1));
		w46.Position = 2;
		// Container child hbox15.Gtk.Box+BoxChild
		this.RefreshSaveDevList = new global::Gtk.Button ();
		this.RefreshSaveDevList.CanFocus = true;
		this.RefreshSaveDevList.Name = "RefreshSaveDevList";
		this.RefreshSaveDevList.UseUnderline = true;
		this.RefreshSaveDevList.Label = global::Mono.Unix.Catalog.GetString ("Обновить");
		this.hbox15.Add (this.RefreshSaveDevList);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.RefreshSaveDevList]));
		w47.PackType = ((global::Gtk.PackType)(1));
		w47.Position = 3;
		w47.Expand = false;
		w47.Fill = false;
		this.vbox6.Add (this.hbox15);
		global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox15]));
		w48.Position = 2;
		w48.Expand = false;
		w48.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.SaveImageBtn = new global::Gtk.Button ();
		this.SaveImageBtn.CanFocus = true;
		this.SaveImageBtn.Name = "SaveImageBtn";
		this.SaveImageBtn.UseUnderline = true;
		this.SaveImageBtn.Label = global::Mono.Unix.Catalog.GetString ("Создать образ");
		this.vbox6.Add (this.SaveImageBtn);
		global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.SaveImageBtn]));
		w49.Position = 3;
		w49.Expand = false;
		w49.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox16 = new global::Gtk.HBox ();
		this.hbox16.Name = "hbox16";
		this.hbox16.Spacing = 6;
		// Container child hbox16.Gtk.Box+BoxChild
		this.label19 = new global::Gtk.Label ();
		this.label19.Name = "label19";
		this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Прогресс выполнения:");
		this.hbox16.Add (this.label19);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.label19]));
		w50.Position = 0;
		w50.Expand = false;
		w50.Fill = false;
		// Container child hbox16.Gtk.Box+BoxChild
		this.CreateImageProgress = new global::Gtk.ProgressBar ();
		this.CreateImageProgress.HeightRequest = 30;
		this.CreateImageProgress.Name = "CreateImageProgress";
		this.hbox16.Add (this.CreateImageProgress);
		global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.CreateImageProgress]));
		w51.Position = 1;
		this.vbox6.Add (this.hbox16);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox16]));
		w52.Position = 4;
		w52.Expand = false;
		w52.Fill = false;
		this.notebook1.Add (this.vbox6);
		global::Gtk.Notebook.NotebookChild w53 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox6]));
		w53.Position = 2;
		// Notebook tab
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Создание образа");
		this.notebook1.SetTabLabel (this.vbox6, this.label6);
		this.label6.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox ();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.ManualDelDevName = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Указать вручную"));
		this.ManualDelDevName.CanFocus = true;
		this.ManualDelDevName.Name = "ManualDelDevName";
		this.ManualDelDevName.DrawIndicator = true;
		this.ManualDelDevName.UseUnderline = true;
		this.ManualDelDevName.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.hbox11.Add (this.ManualDelDevName);
		global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.ManualDelDevName]));
		w54.Position = 0;
		// Container child hbox11.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("sd(");
		this.hbox11.Add (this.label4);
		global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.label4]));
		w55.Position = 1;
		w55.Expand = false;
		w55.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.DelDevWord = new global::Gtk.Entry ();
		this.DelDevWord.WidthRequest = 30;
		this.DelDevWord.CanFocus = true;
		this.DelDevWord.Name = "DelDevWord";
		this.DelDevWord.IsEditable = true;
		this.DelDevWord.WidthChars = 0;
		this.DelDevWord.MaxLength = 2;
		this.DelDevWord.InvisibleChar = '•';
		this.hbox11.Add (this.DelDevWord);
		global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.DelDevWord]));
		w56.Position = 2;
		w56.Expand = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.label14 = new global::Gtk.Label ();
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString (")");
		this.hbox11.Add (this.label14);
		global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.label14]));
		w57.Position = 3;
		w57.Expand = false;
		w57.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.fixed8 = new global::Gtk.Fixed ();
		this.fixed8.Name = "fixed8";
		this.fixed8.HasWindow = false;
		this.hbox11.Add (this.fixed8);
		global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.fixed8]));
		w58.PackType = ((global::Gtk.PackType)(1));
		w58.Position = 4;
		this.vbox5.Add (this.hbox11);
		global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox11]));
		w59.Position = 0;
		w59.Expand = false;
		w59.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox12 = new global::Gtk.HBox ();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 6;
		// Container child hbox12.Gtk.Box+BoxChild
		this.DelDevNameFromList = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Выбрать из списка"));
		this.DelDevNameFromList.CanFocus = true;
		this.DelDevNameFromList.Name = "DelDevNameFromList";
		this.DelDevNameFromList.DrawIndicator = true;
		this.DelDevNameFromList.UseUnderline = true;
		this.DelDevNameFromList.Group = this.ManualDelDevName.Group;
		this.hbox12.Add (this.DelDevNameFromList);
		global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.DelDevNameFromList]));
		w60.Position = 0;
		// Container child hbox12.Gtk.Box+BoxChild
		this.DelDevList = global::Gtk.ComboBox.NewText ();
		this.DelDevList.WidthRequest = 100;
		this.DelDevList.Name = "DelDevList";
		this.hbox12.Add (this.DelDevList);
		global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.DelDevList]));
		w61.Position = 1;
		w61.Expand = false;
		w61.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.fixed9 = new global::Gtk.Fixed ();
		this.fixed9.Name = "fixed9";
		this.fixed9.HasWindow = false;
		this.hbox12.Add (this.fixed9);
		global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.fixed9]));
		w62.PackType = ((global::Gtk.PackType)(1));
		w62.Position = 2;
		// Container child hbox12.Gtk.Box+BoxChild
		this.RefreshDelDevWord = new global::Gtk.Button ();
		this.RefreshDelDevWord.CanFocus = true;
		this.RefreshDelDevWord.Name = "RefreshDelDevWord";
		this.RefreshDelDevWord.UseUnderline = true;
		this.RefreshDelDevWord.Label = global::Mono.Unix.Catalog.GetString ("Обновить");
		this.hbox12.Add (this.RefreshDelDevWord);
		global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.RefreshDelDevWord]));
		w63.PackType = ((global::Gtk.PackType)(1));
		w63.Position = 3;
		w63.Expand = false;
		w63.Fill = false;
		this.vbox5.Add (this.hbox12);
		global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox12]));
		w64.Position = 1;
		w64.Expand = false;
		w64.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.DisconnectDeviceBtn = new global::Gtk.Button ();
		this.DisconnectDeviceBtn.CanFocus = true;
		this.DisconnectDeviceBtn.Name = "DisconnectDeviceBtn";
		this.DisconnectDeviceBtn.UseUnderline = true;
		this.DisconnectDeviceBtn.Label = global::Mono.Unix.Catalog.GetString ("Отключить");
		this.vbox5.Add (this.DisconnectDeviceBtn);
		global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.DisconnectDeviceBtn]));
		w65.Position = 2;
		w65.Expand = false;
		w65.Fill = false;
		this.notebook1.Add (this.vbox5);
		global::Gtk.Notebook.NotebookChild w66 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox5]));
		w66.Position = 3;
		// Notebook tab
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Отключение НЖМД");
		this.notebook1.SetTabLabel (this.vbox5, this.label5);
		this.label5.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Командная оболочка:");
		this.hbox4.Add (this.label8);
		global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label8]));
		w67.Position = 0;
		w67.Expand = false;
		w67.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.CfgCmdShell = new global::Gtk.Entry ();
		this.CfgCmdShell.CanFocus = true;
		this.CfgCmdShell.Name = "CfgCmdShell";
		this.CfgCmdShell.IsEditable = true;
		this.CfgCmdShell.InvisibleChar = '•';
		this.hbox4.Add (this.CfgCmdShell);
		global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.CfgCmdShell]));
		w68.Position = 1;
		this.vbox3.Add (this.hbox4);
		global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox4]));
		w69.Position = 0;
		w69.Expand = false;
		w69.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Partimage-ng:");
		this.hbox5.Add (this.label9);
		global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label9]));
		w70.Position = 0;
		w70.Expand = false;
		w70.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.CfgPartImage = new global::Gtk.Entry ();
		this.CfgPartImage.CanFocus = true;
		this.CfgPartImage.Name = "CfgPartImage";
		this.CfgPartImage.IsEditable = true;
		this.CfgPartImage.InvisibleChar = '•';
		this.hbox5.Add (this.CfgPartImage);
		global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.CfgPartImage]));
		w71.Position = 1;
		this.vbox3.Add (this.hbox5);
		global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox5]));
		w72.Position = 1;
		w72.Expand = false;
		w72.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.fixed5 = new global::Gtk.Fixed ();
		this.fixed5.Name = "fixed5";
		this.fixed5.HasWindow = false;
		this.vbox7.Add (this.fixed5);
		global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.fixed5]));
		w73.Position = 0;
		w73.Expand = false;
		w73.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.fixed4 = new global::Gtk.Fixed ();
		this.fixed4.Name = "fixed4";
		this.fixed4.HasWindow = false;
		this.hbox6.Add (this.fixed4);
		global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.fixed4]));
		w74.Position = 0;
		// Container child hbox6.Gtk.Box+BoxChild
		this.ApplyConfig = new global::Gtk.Button ();
		this.ApplyConfig.CanFocus = true;
		this.ApplyConfig.Name = "ApplyConfig";
		this.ApplyConfig.UseUnderline = true;
		this.ApplyConfig.Label = global::Mono.Unix.Catalog.GetString ("Применить");
		this.hbox6.Add (this.ApplyConfig);
		global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.ApplyConfig]));
		w75.Position = 1;
		w75.Expand = false;
		w75.Fill = false;
		this.vbox7.Add (this.hbox6);
		global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox6]));
		w76.Position = 1;
		w76.Expand = false;
		w76.Fill = false;
		this.vbox3.Add (this.vbox7);
		global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox7]));
		w77.Position = 2;
		w77.Expand = false;
		w77.Fill = false;
		this.notebook1.Add (this.vbox3);
		global::Gtk.Notebook.NotebookChild w78 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox3]));
		w78.Position = 4;
		// Notebook tab
		this.label16 = new global::Gtk.Label ();
		this.label16.Name = "label16";
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Настройки");
		this.notebook1.SetTabLabel (this.vbox3, this.label16);
		this.label16.ShowAll ();
		this.vbox1.Add (this.notebook1);
		global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook1]));
		w79.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vbox8 = new global::Gtk.VBox ();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox17 = new global::Gtk.HBox ();
		this.hbox17.Name = "hbox17";
		this.hbox17.Spacing = 6;
		// Container child hbox17.Gtk.Box+BoxChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		this.hbox17.Add (this.fixed1);
		global::Gtk.Box.BoxChild w80 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.fixed1]));
		w80.PackType = ((global::Gtk.PackType)(1));
		w80.Position = 0;
		this.vbox8.Add (this.hbox17);
		global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox17]));
		w81.Position = 0;
		w81.Expand = false;
		w81.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox19 = new global::Gtk.HBox ();
		this.hbox19.Name = "hbox19";
		this.hbox19.Spacing = 6;
		// Container child hbox19.Gtk.Box+BoxChild
		this.fixed13 = new global::Gtk.Fixed ();
		this.fixed13.Name = "fixed13";
		this.fixed13.HasWindow = false;
		this.hbox19.Add (this.fixed13);
		global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.fixed13]));
		w82.PackType = ((global::Gtk.PackType)(1));
		w82.Position = 0;
		this.vbox8.Add (this.hbox19);
		global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox19]));
		w83.Position = 1;
		w83.Expand = false;
		w83.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.fixed14 = new global::Gtk.Fixed ();
		this.fixed14.HeightRequest = 5;
		this.fixed14.Name = "fixed14";
		this.fixed14.HasWindow = false;
		this.vbox8.Add (this.fixed14);
		global::Gtk.Box.BoxChild w84 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.fixed14]));
		w84.PackType = ((global::Gtk.PackType)(1));
		w84.Position = 2;
		w84.Expand = false;
		w84.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox20 = new global::Gtk.HBox ();
		this.hbox20.Name = "hbox20";
		this.hbox20.Spacing = 6;
		// Container child hbox20.Gtk.Box+BoxChild
		this.AutoSaveImage = new global::Gtk.Button ();
		this.AutoSaveImage.CanFocus = true;
		this.AutoSaveImage.Name = "AutoSaveImage";
		this.AutoSaveImage.UseUnderline = true;
		this.AutoSaveImage.Label = global::Mono.Unix.Catalog.GetString ("Создать образ");
		this.hbox20.Add (this.AutoSaveImage);
		global::Gtk.Box.BoxChild w85 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.AutoSaveImage]));
		w85.Position = 0;
		// Container child hbox20.Gtk.Box+BoxChild
		this.AutoUnpackImage = new global::Gtk.Button ();
		this.AutoUnpackImage.CanFocus = true;
		this.AutoUnpackImage.Name = "AutoUnpackImage";
		this.AutoUnpackImage.UseUnderline = true;
		this.AutoUnpackImage.Label = global::Mono.Unix.Catalog.GetString ("Распаковать образ");
		this.hbox20.Add (this.AutoUnpackImage);
		global::Gtk.Box.BoxChild w86 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.AutoUnpackImage]));
		w86.PackType = ((global::Gtk.PackType)(1));
		w86.Position = 1;
		this.vbox8.Add (this.hbox20);
		global::Gtk.Box.BoxChild w87 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox20]));
		w87.PackType = ((global::Gtk.PackType)(1));
		w87.Position = 3;
		w87.Expand = false;
		w87.Fill = false;
		this.GtkAlignment.Add (this.vbox8);
		this.frame1.Add (this.GtkAlignment);
		this.GtkLabel24 = new global::Gtk.Label ();
		this.GtkLabel24.Name = "GtkLabel24";
		this.GtkLabel24.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Авто</b>");
		this.GtkLabel24.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel24;
		this.vbox1.Add (this.frame1);
		global::Gtk.Box.BoxChild w90 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame1]));
		w90.Position = 1;
		w90.Expand = false;
		w90.Fill = false;
		this.vpaned1.Add (this.vbox1);
		global::Gtk.Paned.PanedChild w91 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.vbox1]));
		w91.Resize = false;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.vbox9 = new global::Gtk.VBox ();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		// Container child vbox9.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.LogView = new global::Gtk.NodeView ();
		this.LogView.CanFocus = true;
		this.LogView.Name = "LogView";
		this.GtkScrolledWindow.Add (this.LogView);
		this.vbox9.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w93 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.GtkScrolledWindow]));
		w93.Position = 0;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hbox21 = new global::Gtk.HBox ();
		this.hbox21.Name = "hbox21";
		this.hbox21.Spacing = 6;
		// Container child hbox21.Gtk.Box+BoxChild
		this.ShowAbout = new global::Gtk.Button ();
		this.ShowAbout.CanFocus = true;
		this.ShowAbout.Name = "ShowAbout";
		this.ShowAbout.UseUnderline = true;
		this.ShowAbout.Label = global::Mono.Unix.Catalog.GetString ("О программе");
		this.hbox21.Add (this.ShowAbout);
		global::Gtk.Box.BoxChild w94 = ((global::Gtk.Box.BoxChild)(this.hbox21 [this.ShowAbout]));
		w94.Position = 0;
		w94.Expand = false;
		w94.Fill = false;
		// Container child hbox21.Gtk.Box+BoxChild
		this.fixed15 = new global::Gtk.Fixed ();
		this.fixed15.Name = "fixed15";
		this.fixed15.HasWindow = false;
		this.hbox21.Add (this.fixed15);
		global::Gtk.Box.BoxChild w95 = ((global::Gtk.Box.BoxChild)(this.hbox21 [this.fixed15]));
		w95.Position = 1;
		// Container child hbox21.Gtk.Box+BoxChild
		this.ClearLog = new global::Gtk.Button ();
		this.ClearLog.CanFocus = true;
		this.ClearLog.Name = "ClearLog";
		this.ClearLog.UseUnderline = true;
		this.ClearLog.Label = global::Mono.Unix.Catalog.GetString ("Очистить");
		this.hbox21.Add (this.ClearLog);
		global::Gtk.Box.BoxChild w96 = ((global::Gtk.Box.BoxChild)(this.hbox21 [this.ClearLog]));
		w96.Position = 2;
		w96.Expand = false;
		w96.Fill = false;
		// Container child hbox21.Gtk.Box+BoxChild
		this.SaveLog = new global::Gtk.Button ();
		this.SaveLog.CanFocus = true;
		this.SaveLog.Name = "SaveLog";
		this.SaveLog.UseUnderline = true;
		this.SaveLog.Label = global::Mono.Unix.Catalog.GetString ("Сохранить");
		this.hbox21.Add (this.SaveLog);
		global::Gtk.Box.BoxChild w97 = ((global::Gtk.Box.BoxChild)(this.hbox21 [this.SaveLog]));
		w97.Position = 3;
		w97.Expand = false;
		w97.Fill = false;
		this.vbox9.Add (this.hbox21);
		global::Gtk.Box.BoxChild w98 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hbox21]));
		w98.Position = 1;
		w98.Expand = false;
		w98.Fill = false;
		this.vpaned1.Add (this.vbox9);
		this.Add (this.vpaned1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 811;
		this.DefaultHeight = 459;
		this.Show ();
		this.RefreshHostList.Clicked += new global::System.EventHandler (this.OnRefreshHostListClicked);
		this.StartScan.Clicked += new global::System.EventHandler (this.OnStartScanClicked);
		this.ImageFileOpenButton.SelectionChanged += new global::System.EventHandler (this.OnImageFileOpenButtonSelectionChanged);
		this.RefreshDevList.Clicked += new global::System.EventHandler (this.OnRefreshDevListClicked);
		this.SaveImageButton.Clicked += new global::System.EventHandler (this.OnSaveImageButtonClicked);
		this.RefreshSaveDevList.Clicked += new global::System.EventHandler (this.OnRefreshSaveDevListClicked);
		this.SaveImageBtn.Clicked += new global::System.EventHandler (this.OnSaveImageBtnClicked);
		this.RefreshDelDevWord.Clicked += new global::System.EventHandler (this.OnRefreshDelDevWordClicked);
		this.DisconnectDeviceBtn.Clicked += new global::System.EventHandler (this.OnDisconnectDeviceBtnClicked);
		this.ApplyConfig.Clicked += new global::System.EventHandler (this.OnApplyConfigClicked);
		this.AutoSaveImage.Clicked += new global::System.EventHandler (this.OnAutoSaveImageClicked);
		this.AutoUnpackImage.Clicked += new global::System.EventHandler (this.OnAutoUnpackImageClicked);
		this.ShowAbout.Clicked += new global::System.EventHandler (this.OnShowAboutClicked);
		this.ClearLog.Clicked += new global::System.EventHandler (this.OnClearLogClicked);
		this.SaveLog.Clicked += new global::System.EventHandler (this.OnSaveLogClicked);
	}
}
